name = "filiphajek-sk"
account_id = "fdd968b02324cff921f74c4f5b4c1e93"
main = "dist/filiphajek_sk/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "filiphajek.sk", custom_domain = true },
  { pattern = "www.filiphajek.sk", custom_domain = true },
]

[assets]
directory = "./dist/client"

# Secrets are set via: wrangler secret put TURNSTILE_SECRET_KEY
# Secrets are set via: wrangler secret put RESEND_API_KEY
