name = "filiphajek-sk"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Secrets are set via: wrangler secret put TURNSTILE_SECRET_KEY
# Secrets are set via: wrangler secret put RESEND_API_KEY
